let numbers=[1, 2, 3];
console.log("Before push:", numbers);
console.log(numbers[2]);
console.log("Length before push:", numbers.length);
numbers.push(4,5,6);
console.log("After push:", numbers);
console.log("Length after push:", numbers.length);
console.log(numbers[5]);
numbers.push('wazed');
console.log("After pushing a string:", numbers);
console.log("Length after pushing a string:", numbers.length);
console.log(numbers[6]);
console.log(numbers);
numbers.pop();
console.log("After pop:", numbers);
console.log("Length after pop:", numbers.length);
console.log(numbers);
numbers.shift();
console.log("After shift:", numbers);
console.log("Length after shift:", numbers.length);
console.log(numbers);
numbers.unshift(0,1);
console.log("After unshift:", numbers);
console.log("Length after unshift:", numbers.length);
console.log(numbers);